#!/usr/bin/bash

THEME_DIR=$1

# Set the breaking bad wallpaper
killall swaybg
swaybg -m fill -i $THEME_DIR/wallpaper/breakingbad.jpg &

# Enable the dunst notification daemon with the breaking bad theme
killall dunst
dunst -config $THEME_DIR/dunst/dunstrc &

# Set the kitty terminal theme to breaking bad
# INFO: this destroys your old kitty config
mkdir -p ~/.config/kitty/themes
cp $THEME_DIR/kitty/BreakingBad.conf ~/.config/kitty/themes/
cp $THEME_DIR/kitty/kitty.conf ~/.config/kitty/kitty.conf
kitty +kitten themes --reload-in=all "Breaking Bad"

# Set the rofi theme to breaking bad
# INFO: this destroys your old rofi config
mkdir -p ~/.config/rofi/themes
cp $THEME_DIR/rofi/breaking-bad.rasi ~/.config/rofi/themes/
cp $THEME_DIR/rofi/config.rasi ~/.config/rofi/config.rasi

# Set the swaylock theme to breaking bad
# INFO: this destroys your old swaylock config
unlink ~/.config/swaylock 2> /dev/null || rm -rf ~/.config/swaylock/
cp -r $THEME_DIR/swaylock ~/.config/swaylock

# Set the waybar theme to breaking bad
killall waybar
waybar -c $THEME_DIR/waybar/config.jsonc -s $THEME_DIR/waybar/style.css &

# Set the wlogout theme to breaking bad
# INFO: this destroys your old wlogout config
unlink ~/.config/wlogout 2> /dev/null || rm -rf ~/.config/wlogout/
cp -r $THEME_DIR/wlogout ~/.config/wlogout

# Set GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "BreakingBad"
gsettings set org.gnome.desktop.interface icon-theme "Reversal-green-dark"
