[theme]
name = "Breaking Bad"
desc = "Glass Grade Hyprland Theme"
version = "0.1.0"
author = "alexjercan"
git = "github.com/alexjercan/breakingbad-hyprland-theme"
config = "theme.conf"

[kill]
exclude_bar = ["waybar"]
exclude_wallpaper = ["swaybg"]
